// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPmT-rNoKrp8o525ndfUjItm4dcwLdUFo',
    appId: '1:597579805332:web:482be34f3be5ff70af3a81',
    messagingSenderId: '597579805332',
    projectId: 'budget-tracker-73c41',
    authDomain: 'budget-tracker-73c41.firebaseapp.com',
    storageBucket: 'budget-tracker-73c41.firebasestorage.app',
    measurementId: 'G-MB195TL173',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz8TiuAaRhInhi_J_tRoEJYX7uC96GD7U',
    appId: '1:597579805332:android:c150bf34d54b65e9af3a81',
    messagingSenderId: '597579805332',
    projectId: 'budget-tracker-73c41',
    storageBucket: 'budget-tracker-73c41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRBqUnT3vpt1UBPPj5gBHPz8WPQUQ1LxI',
    appId: '1:597579805332:ios:e46c0ec48e2593f3af3a81',
    messagingSenderId: '597579805332',
    projectId: 'budget-tracker-73c41',
    storageBucket: 'budget-tracker-73c41.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRBqUnT3vpt1UBPPj5gBHPz8WPQUQ1LxI',
    appId: '1:597579805332:ios:e46c0ec48e2593f3af3a81',
    messagingSenderId: '597579805332',
    projectId: 'budget-tracker-73c41',
    storageBucket: 'budget-tracker-73c41.firebasestorage.app',
    iosBundleId: 'com.example.budgetTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPmT-rNoKrp8o525ndfUjItm4dcwLdUFo',
    appId: '1:597579805332:web:41926f5c5662b00aaf3a81',
    messagingSenderId: '597579805332',
    projectId: 'budget-tracker-73c41',
    authDomain: 'budget-tracker-73c41.firebaseapp.com',
    storageBucket: 'budget-tracker-73c41.firebasestorage.app',
    measurementId: 'G-BY5CSE3Q8S',
  );
}
